- name: Validate structure of volumes input
  ansible.builtin.assert:
    that:
      - volumes | aursu.lvm_setup.validate_volumes_input
    fail_msg: "Invalid structure in 'volumes' input."

- name: Get current LVM info
  aursu.general.lvm_info:
    filter: vgs,lvs
  register: lvm_info

- debug: var=lvm_info
  when: debug_mode | default(false)

- name: Validate if Volume group exists
  ansible.builtin.assert:
    that:
      - vg_name | aursu.lvm_setup.validate_vg(lvm_info)
    fail_msg: "Volume group {{ vg_name }} not found in system."
