- name: Determine if partitions input should be processed
  ansible.builtin.set_fact:
    process_partitions: "{{ partitions is defined and partitions | length > 0 }}"

- block:
    - name: Validate input and prerequisites
      import_tasks: validate.yml

    - name: Process each disk defined in partitions
      ansible.builtin.include_tasks: process.yml
      loop: "{{ partitions | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        disk: "{{ item.key }}"
        parts: "{{ item.value }}"
  when: process_partitions

- block:
    - debug: msg="Skip processing if partitions variable is undefined or empty"
      when: debug_mode | default(false)
  when: not process_partitions
