---
galaxy_info:
  author: Alexander Ursu
  description: >
    Ansible role to manage and validate disk partitioning.
    Supports declarative partition definitions, validation against existing layouts,
    and generation of partition creation plans with alignment handling.
  license: MIT
  min_ansible_version: 2.14
  platforms:
    - name: EL
      versions: [9]
    - name: Ubuntu
      versions: [22.04, 24.04]
  galaxy_tags:
    - partitions
    - disks
    - lvm
    - storage
    - linux
dependencies: []
