- name: Create LVM setup on host
  hosts: all
  become: true

  vars:
    debug_mode: false

  roles:
    - role: aursu.lvm_setup.process_disks
      vars:
        validate_partitions: true

    - role: aursu.lvm_setup.process_lvm
      vars:
        validate_partitions: false

    - aursu.lvm_setup.process_volumes
